# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1eebb2c6dcd80eaab87b00d8cda08f9e177ec9b324f43429e9c28f18cb69a39cc413900b163e7f51f77e2a0d8716a0ca048c55fa5cb2ce3c2ab81728d67f02d7

test:
  secret_key_base: aad29872b79b7fd409762e580f60f2518745dfbfbbf2a060f18cd52f8e22a5561ce3066e210ccbf11c7f24c4beabea7e47d938c6f879ade4cc624f50c3210535

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
